# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: test and run archiever

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2.1.0
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: dist-newstyle　~/.ghcup
          # An explicit key for restoring and saving the cache
          key: key
      - run: |
          curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
          ~/.ghcup/bin/ghcup install 8.8.3
          cd archiever
          ~/.ghcup/bin/cabal v2-build
          ~/.ghcup/bin/cabal v2-test
          ~/.ghcup/bin/cabal v2-exec archieve
