# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: test and run archiever

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2.1.0
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: dist-newstyle　~/.ghcup
          # An explicit key for restoring and saving the cache
          key: key
      - run: echo $HOME
      - run: 
          sudo apt install build-essential curl libffi-dev libffi6 libgmp-dev libgmp10 libncurses-dev libncurses5 libtinfo5;
          curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh;
          ~/.ghcup/bin/ghcup install 8.8.3;
          ~/.ghcup/bin/ghc --version
          which ghc;
          cd $GITHUB_WORKSPACE/archiever;
          which ghc;
          ~/.ghcup/bin/cabal --with-compiler=/home/runner/work/.ghcup/bin/ghc v2-build;
          ~/.ghcup/bin/cabal --with-compiler=/home/runner/work/.ghcup/bin/ghc v2-test;
          ~/.ghcup/bin/cabal --with-compiler=/home/runner/work/.ghcup/bin/ghc v2-exec archieve
        env:
          PATH: "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:~/.ghcup/bin"
