# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: test and run archiever

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2.1.0
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: |
            dist-newstyle
            ~/.cabal
          # An explicit key for restoring and saving the cache
          key: key2
      - name: build
        run: |
          cabal update
          cd $GITHUB_WORKSPACE/archiever
          cabal v2-build
      - name: test
        run: |
          cd $GITHUB_WORKSPACE/archiever      
          cabal v2-test
      - name: run archieve
        run: |
          cd $GITHUB_WORKSPACE/archiever          
          cabal v2-exec archieve
      - name: Commit files
        run: |
          sudo apt install git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || git commit -m "apply archiever action" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
